### ISSUE TITLE
CURL - Endpoint Incluir Anexo Arquivo

### ISSUE THREAD

**Issue by hugorn** [omiexperience/api-examples#14]
Ao tentar efetuar o post através de Curl enviando o json como file está dando a mensagem:

{"status":"error","message":"Invalid JSON object"}

Comando:
 curl https://app.omie.com.br/api/v1/geral/anexo/ -H "Content-type: application/json" -d @envio.json

Obs: O mesmo arquivo json funciona corretamente via Postman. (Contém um pdf zipado, base64 e seu hash md5)
[envio.zip](https://github.com/omiexperience/api-examples/files/11315233/envio.zip)

**Comment by hugorn** [comment]
@igorhmm pode me dar uma ajuda?

**Comment by marcusguarani** [comment]
Veja a doc da api creio que você precisa converter o arquivo em base64 para
enviar na maioria dos casos!
 Ou então fazer um ajax com multipart/form-data

marcusguarani



Em seg., 24 de abr. de 2023 21:05, Hugo Santos ***@***.***>
escreveu:

**Comment by hugorn** [comment]
Já está base64 o arquivo

**Comment by marcusguarani** [comment]
Tente enviar como string então.

marcusguarani

Em seg., 24 de abr. de 2023 21:43, Hugo Santos ***@***.***>
escreveu:

**Comment by hugorn** [comment]
É isso que o parâmetro -d do curl está fazendo, como o json é extenso o comando não aceita como string diretamente, então o conteúdo está sendo passado wk formato referenciado de arquivo usando @

**Comment by hugorn** [comment]
@marcusguarani Consegui descobrir o problema, Dentro do json o faltou abrir os colchetes para a tag param. Após o ajuste deu certo, segue como ficou:
{
  "call": "IncluirAnexo",
  "app_key": "xxxxxxxxxxxxxxx",
  "app_secret": "yyyyyyyyyyyyyyyyyyyyy",
  "param": **[**
    {
      "cCodIntAnexo": "503710",
      "cTabela": "conta-pagar",
      "nId": 2073686591,
      "cNomeArquivo": "temp.pdf",
      "cTipoArquivo": "pdf",
      "cArquivo": "asfsc15a1f65sd4f6asdf4sd6f4sad6fas4f5s4fsdfa4f6f4a4fdf4sad4fsd4df",
      "cMd5": "a378e4a41a684a560deaa9eb06a12385"
    }
  **]**
}

**Comment by marcusguarani** [comment]
Show 👍🏽

marcusguarani

Em ter., 25 de abr. de 2023 05:12, Hugo Santos ***@***.***>
escreveu:
