### ISSUE TITLE
Não consegui

### ISSUE THREAD

**Issue by diegolsr** [omiexperience/api-examples#2]
Tentei usar o código do vb6 aqui e não consegui. Pode me ajudar?

**Comment by igorhmm** [comment]
Oi Diego,

Acho que precisamos de mais informações pra te ajudar :-)

O que você não conseguiu? Você conseguiu baixar o fonte e executar? Deu alguma mensagem de erro?

**Comment by diegolsr** [comment]
Opa!
Então Igor,
Abri o Microsoft Visual Studio e criei um aplicativo Windows Forms .net framework (vb6), peguei o exemplo vb6 do módulos que você postou e coloquei no aplicativo.  Coloquei o appKey e a appSecret. Executei o código e deu um erro de parâmetro.
![capturar](https://user-images.githubusercontent.com/33271727/39203860-740b71c0-47cc-11e8-8965-4daa08daff0e.PNG)

**Comment by diegolsr** [comment]
Alguém me ajuda?

**Comment by igorhmm** [comment]
Bom dia Diego,

Vou testar com o pessoal aqui e te aviso... se puder compartilhar o seu projeto (sem o app_secret) com a gente ajudaria bastante :-)

**Comment by diegolsr** [comment]
Bom dia
Anexei o project aqui.

[Omiê.zip](https://github.com/omiexperience/api-examples/files/1955099/Omie.zip)

**Comment by diegolsr** [comment]
Alguém me ajuda? Por favor?

**Comment by diegolsr** [comment]
Como faz o loop para pegar todas as paginas? Porque só mostra um página...
{
  "pagina": 1,
  "total_de_paginas": 19,
  "registros": 50,
  "total_de_registros": 909,
  "conta_receber_cadastro": [
    {
      "bloqueado": "N",
      "bloquear_baixa": "N",
      "boleto": {
        "cGerado": "",
        "cNumBancario": "",
        "cNumBoleto": "",
        "dDtEmBol": "",
        "nPerJuros": 0,
        "nPerMulta": 0
      }

**Comment by igorhmm** [comment]
Oi Diego,

Na sua requisição... basta colocar o número da página que você deseja retornar. Exemplo:

http://click.omie.com/developer-0pj3rqvgh

Se você preferir, também pode pedir ajuda no chat que tem disponível no nosso site :-)

Abraços
