### ISSUE TITLE
Não achei exemplo em PHP

### ISSUE THREAD

**Issue by edilsonsp** [omiexperience/api-examples#3]
Ola estou usando PHP 5.6 em Servidor Linux,

Temos algum exemplo em PHP pois nosso Sistema ERP esta em plataforma Cloud.

**Comment by fernandoalfred** [comment]
Bom dia Edilson,

Para ver os exemplos basta acessar nosso portal do desenvolvedor http://developer.omie.com.br e no menu superior, clicar em "Exemplos". Lá você encontrará uma lista de exemplos em algumas das linguagens mais utilizadas, incluindo o PHP.

Caso tenha alguma dúvida com relação às nossas API's o nosso chat estará disponível para te ajudar com o que precisar.

Atenciosamente

Fernando
