### ISSUE TITLE
Conectar via Webhook

### ISSUE THREAD

**Issue by ehduardu** [omiexperience/api-examples#8]
Olá pessoal, 

Gostaria de solicitar um webhook do lado do Omie, isso iria ajudar muito aos apps que fazem requisição no Omie e também seria melhor para o próprio servidor de vocês, pois iria diminuir o número de chamadas. 

Por exemplo:

No meu cenário, criamos uma rotina para constantemente ficar fazendo chamadas ao Omie, e verificando se teve atualização nas Ordens de Serviço. Porém isso não é a melhor forma de fazer, e recentemente estamos recebendo muitos erros, como esse: 

SOAP-ENV:Client-8020 - ERROR: Esta requisição já foi processada ou está sendo processada e você pode tentar novamente às 10:06:26. (1) - Em 12/11/2020 10:05

Isso gera muitos problemas, pois temos que tentar novamente as chamadas depois de um tempo, aumentando o número de requisições no servidor de vocês.

Esse tipo de coisa se resolveria com um webhook, onde no caso ficaria esperando alguma alteração na Ordem de Serviço. 

Acredito que é uma mudança pra ambas as partes, este é meu feedback.

**Comment by magnosanttana** [comment]
oi @ehduardu  tudo bem? O omie possui Webhook, https://developer.omie.com.br/my-apps/ nesse link ai, ao selecionar um aplicativo ele mostra a opção de cadastrar um webhook...

Mas eu comecei a testá-lo aqui e pelo menos a parte de contas a receber, parece que não ta rolando as notificações. Mas ainda to verificando se fiz algo errado...

Tente ai tb e registra aqui se teve sucesso... um abraço!

![image](https://user-images.githubusercontent.com/4489973/100034287-a3d99c00-2dda-11eb-90b1-f5e22be06e6a.png)

**Comment by ehduardu** [comment]
Oi @magnosanttana, desculpa a demora pra responder

Consegui o acesso aos webhooks sim.

Utilizei os tópicos para pegar as notificações das contas a receber:

- Financas.ContaReceber.BaixaRealizada
- Financas.ContaReceber.Alterado
